{% set version = "0.4.1" %}

package:
  name: jupyter_server_terminals
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter-server-terminals/jupyter_server_terminals-{{ version }}.tar.gz
  sha256: de1e31a286146a2edfaabd1653cadbb59f566f49e1667cc557e2804079ec3570

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - hatchling >=1.5
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - terminado >=0.8.3
    # - pywinpty >=2.0.3  # rely on terminado to provide this

test:
  source_files:
    - tests
  imports:
    - jupyter_server_terminals
  commands:
    - pip check
    # TODO: testing after https://github.com/conda-forge/jupyter_server-feedstock/issues/101
  requires:
    - pip

about:
  home: https://github.com/jupyter-server/jupyter_server_terminals
  summary: A Jupyter Server Extension Providing Terminals.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/jupyter_server
