{% set name = "jupyter_server_terminals" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 57ab779797c25a7ba68e97bcfb5d7740f2b5e8a83b5e8102b10438041a7eac5d

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0
  skip: true # [py<38]

requirements:
  host:
    - hatchling >=1.5
    - pip
    - python
    - wheel
  run:
    - python
    - terminado >=0.8.3
    - pywinpty >=2.0.10 # [win]

test:
  source_files:
    - tests
  imports:
    - jupyter_server_terminals
  commands:
    - pip check
    - pytest -vv --cov=jupyter_server_terminals --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=80
  requires:
    - jupyter_server >=2.0.0rc8
    - pip
    - pytest >=7.0
    - pytest-cov
    - pytest-jupyter-server >=0.5.3
    - pytest-timeout

about:
  home: https://github.com/jupyter-server/jupyter_server_terminals
  summary: A Jupyter Server Extension Providing Terminals.
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  description: Jupyter Server Terminals is a Jupyter Server Extension providing support for terminals.
  doc_url: https://github.com/jupyter-server/jupyter_server_terminals#readme
  dev_url: https://github.com/jupyter-server/jupyter_server_terminals
  
extra:
  recipe-maintainers:
    - conda-forge/jupyter_server
